version: "3.3"
services:
  server:
    image: node:16-alpine
    container_name: server-container
    command: sh -c "yarn install  && yarn start"
    volumes:
      - ./server:/var/service/app
    working_dir: /var/service/app
    ports:
      - "3040:3040"
    restart: "always"
    networks:
      - webproxy
  client-user:
    image: node:16-alpine
    ports:
      - "3000:3000"
    command: sh -c "yarn install && yarn build  && yarn start"
    volumes:
      - ./client-user:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    working_dir: /usr/src/app
    restart: always
    networks:
      - webproxy
  cache:
    image: "redis:5.0.8-alpine"
    container_name: "redis-cache"
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'redis-cli PING'"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: "on-failure"
    networks:
      - webproxy
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    # command: [--auth]
    restart: always

  # struct-service:
  #   build: "./struct-service"
  #   volumes:
  #     - ./struct-service:/opt/app
  #   ports:
  #     - 4000:4000
networks:
  webproxy:
    driver: bridge
